version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: 
    environment:
      PGADMIN_DEFAULT_EMAIL: ""
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "7070:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
volumes:
  postgres-data:
  
networks: 
  postgres-compose-network:
    driver: bridge